<%--
/*********************************************************************
 * Glacier Point Project - Address book page
 * Date: 6/10/2014
 * By: Amrit Panesar - 77260
 *********************************************************************/
 --%>
<%@ Page Language="C#" MasterPageFile="~/GlacierPoint.Master" AutoEventWireup="true"
    CodeBehind="AddressBook.aspx.cs" Inherits="GlacierPoint.AddressBook" Title="GlacierPoint Address Book" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Address Book</h1>
    <asp:LinkButton ID="addEmployeeButton" runat="server" Text="Add New Employee" OnClick="addEmployeeButton_Click" /><br />
    <asp:GridView ID="grid" runat="server" AutoGenerateColumns="False" 
        CellPadding="4" AllowPaging="True"
        AllowSorting="True" DataKeyNames="EmployeeId" DataSourceID="employeesSqlDataSource"
        PageSize="3" EnableModelValidation="True" ForeColor="#333333" 
        GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <Columns>
            <asp:BoundField DataField="Name" HeaderText="Name" />
            <asp:BoundField DataField="City" HeaderText="City" />
            <asp:BoundField DataField="MobilePhone" HeaderText="Mobile Phone" />
            <asp:ButtonField CommandName="Select" Text="Select" />
        </Columns>
        <EditRowStyle BackColor="#999999" />
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
    </asp:GridView>
    <asp:SqlDataSource ID="employeeDetailSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:GlacierPoint %>"
        DeleteCommand="DELETE FROM [gp_Employee] WHERE [EmployeeId] = @EmployeeId" InsertCommand="INSERT INTO [gp_Employee] ([DepartmentId], [Name], [Username], [Password], [Address], [City], [State], [Zip], [HomePhone], [Extension], [MobilePhone]) VALUES (@DepartmentId, @Name, @Username, @Password, @Address, @City, @State, @Zip, @HomePhone, @Extension, @MobilePhone)"
        SelectCommand="SELECT [EmployeeId], [DepartmentId], [Name], [Username], [Password], [Address], [City], [State], [Zip], [HomePhone], [Extension], [MobilePhone] FROM [gp_Employee] WHERE ([EmployeeId] = @EmployeeId)"
        UpdateCommand="UPDATE [gp_Employee] SET [DepartmentId] = @DepartmentId, [Name] = @Name, [Username] = @Username, [Password] = @Password, [Address] = @Address, [City] = @City, [State] = @State, [Zip] = @Zip, [HomePhone] = @HomePhone, [Extension] = @Extension, [MobilePhone] = @MobilePhone WHERE [EmployeeId] = @EmployeeId">
        <SelectParameters>
            <asp:ControlParameter ControlID="grid" Name="EmployeeId" PropertyName="SelectedValue"
                Type="Int32" />
        </SelectParameters>
        <DeleteParameters>
            <asp:Parameter Name="EmployeeId" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="DepartmentId" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
            <asp:Parameter Name="EmployeeId" Type="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="DepartmentId" Type="Int32" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Username" Type="String" />
            <asp:Parameter Name="Password" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="City" Type="String" />
            <asp:Parameter Name="State" Type="String" />
            <asp:Parameter Name="Zip" Type="String" />
            <asp:Parameter Name="HomePhone" Type="String" />
            <asp:Parameter Name="Extension" Type="String" />
            <asp:Parameter Name="MobilePhone" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
    <br />
    <asp:DetailsView ID="employeeDetails" runat="server" AutoGenerateRows="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" AutoGenerateInsertButton="True" DataKeyNames="EmployeeId"
        DataSourceID="employeeDetailSqlDataSource" OnItemDeleted="employeeDetails_ItemDeleted"
        OnItemInserted="employeeDetails_ItemInserted" 
        OnItemUpdated="employeeDetails_ItemUpdated" CellPadding="4" 
        EnableModelValidation="True" ForeColor="#333333" GridLines="None">
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
        <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
        <EditRowStyle BackColor="#999999" />
        <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
        <Fields>
            <asp:BoundField DataField="EmployeeId" HeaderText="EmployeeId" InsertVisible="False"
                ReadOnly="True" SortExpression="EmployeeId" />
            <asp:TemplateField HeaderText="DepartmentId" SortExpression="DepartmentId">
                <EditItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server" DataSourceID="departmentsDataSource"
                        DataTextField="Department" DataValueField="DepartmentId" SelectedValue='<%# Bind("DepartmentId") %>' />
                </EditItemTemplate>
                <InsertItemTemplate>
                    <asp:DropDownList ID="didDdl" runat="server" DataSourceID="departmentsDataSource"
                        DataTextField="Department" DataValueField="DepartmentId" SelectedValue='<%# Bind("DepartmentId") %>' />
                </InsertItemTemplate>
                <ItemTemplate>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
                    <asp:DropDownList ID="didDdl" runat="server" DataSourceID="departmentsDataSource"
                        DataTextField="Department" DataValueField="DepartmentId" SelectedValue='<%# Bind("DepartmentId") %>'
                        Enabled="False" />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
            <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
            <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
            <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
            <asp:BoundField DataField="Zip" HeaderText="Zip" SortExpression="Zip" />
            <asp:BoundField DataField="HomePhone" HeaderText="HomePhone" SortExpression="HomePhone" />
            <asp:BoundField DataField="Extension" HeaderText="Extension" SortExpression="Extension" />
            <asp:BoundField DataField="MobilePhone" HeaderText="MobilePhone" SortExpression="MobilePhone" />
        </Fields>
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <HeaderTemplate>
            <%#Eval("Name") == null? "Adding New Employee" : Eval("Name")%>
        </HeaderTemplate>
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
    </asp:DetailsView>
    <asp:SqlDataSource ID="departmentsDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:GlacierPoint %>"
        SelectCommand="SELECT [DepartmentId], [Department] FROM [gp_Department]"></asp:SqlDataSource>
    <asp:SqlDataSource ID="employeesSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:GlacierPoint %>"
        SelectCommand="SELECT [EmployeeId], [Name], [City], [MobilePhone] FROM [gp_Employee] ORDER BY [Name]">
    </asp:SqlDataSource>
</asp:Content>
